name: "Release"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Init Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.github_token }}
    - name: Build
      run: nix build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: result/bin/invicli
